export const SAVE_JOB_DETAILS_FORM = "SAVE_JOB_DETAILS_FORM";
export const SAVE_JOB_INVOICE_LIST = "SAVE_JOB_INVOICE_LIST";
export const SAVE_JOB_JOB_SUMMARY_LIST = "SAVE_JOB_JOB_SUMMARY_LIST";
export const SAVE_JOB = "SAVE_JOB";
export const CLEAN_JOB = "CLEAN_JOB";

export const SAVE_JOB_ESTIMATE_DETAILS_FORM = "SAVE_JOB_ESTIMATE_DETAILS_FORM";
export const SAVE_JOB_ESTIMATE_INVOICE_LIST = "SAVE_JOB_ESTIMATE_INVOICE_LIST";
export const SAVE_JOB_ESTIMATE_JOB_SUMMARY_LIST = "SAVE_JOB_ESTIMATE_JOB_SUMMARY_LIST";
export const SAVE_JOB_ESTIMATE = "SAVE_JOB_ESTIMATE";
export const CLEAN_JOB_ESTIMATE = "CLEAN_JOB_ESTIMATE";

export const CHANGE_IS_LOADING = "CHANGE_IS_LOADING";

export const SAVE_CLIENT = "SAVE_CLIENT";